### ISSUE TITLE
How do you find the details of each rule in PaloAlto Firewall rules ( an extension of issues #97)

### ISSUE THREAD

**Issue by srkolli** [mpenning/ciscoconfparse#155]
For example you want to know the details for each rule. For example,
 "Rule 1" {
                  from Trust;
                  to Trust;
                  source any;
                  destination any;
                  source-user any;
                  category any;
                  application any;
                  service any;
                  hip-profiles any;
                  action allow;
                  log-start no;
                  log-end yes;
                  negate-source no;
                  negate-destination no;
                  profile-setting {
                    group important-security-tule;
                  }
                  description xxxxxx;
                  tag Internal;
                }

**Comment by mpenning** [comment]
Please consider using the techniques outlined in the docs online:
http://www.pennington.net/py/ciscoconfparse/tutorial_get_config_values.html

There are no preparsed values available for Palo Alto configurations, since I don't have a palo alto configuration to work from.  If you want to donate a complete Palo Alto configuration, that would assist with that goal.
