### ISSUE TITLE
finding JunOS interfaces and addresses

### ISSUE THREAD

**Issue by frederic-loui** [mpenning/ciscoconfparse#177]
Hi, 
Hope you are doing well considering the context (we were in touch long time ago)
I'd need to retrieve interface list from Junos and their related address:
Example:
```
interfaces {                                                 
    xe-0/0/0 {                                               
        unit 0 {                                             
            family inet {                                    
                address 1.1.1.6/31;                     
            }                                                
            family inet6 {                                   
                address FD00:DEAD:CAFE:6000::4/127;         
            }                                                
        }                                                    
    }                                                        
    xe-0/0/1 {                                               
        unit 0 {                                             
            family inet {                                    
                address 2.2.2.10/31;                    
            }                                                
            family inet6 {                                   
                address FD00:DEAD:CAFE:7903::2/64;             
            }                                                
        }                                                    
    }                                                        
    xe-0/0/2 {                                               
        mtu 9192;                                            
        unit 0 {                                             
            family inet {                                    
                address 3.3.3.14/31;                    
            }                                                
            family inet6 {                                   
                address FD00:DEAD:CAFE:6000::26/127;        
            }                                                
        }                                                    
    }                                                        
}

```

I'm attempting to retrieve the interface name using the following reasoning:
```
ipaddr_list=parse.find_children_w_parents("^interface","address")  
for ipaddr in ipaddr_list:    
intfs = parse.find_parents_w_child(r"^    [a-z]{2}",ipaddr)
printf ("%s" % (intfs) )
```

Therefore in this case i get: 
`ipaddr` set to `                address 1.1.1.6/31`
So, `intfs` should find `['    xe-0/0/0 {]`

In my case `intfs` is `[]`

I'm pretty sure i'm doing something wrong.
Don't hesitate to scold me then :)

Merci !
Frederic

**Comment by mpenning** [comment]
Hello Frederick,

The way you're trying to use regular expressions above doesn't work well... you are trying to detect literal spaces, but the literal space-count is off in `intfs = parse.find_parents_w_child(r"^    [a-z]{2}",ipaddr)`.

The smallest number of changes required to make progress is:
```python
intfs = parse.find_parents_w_child(r"^\s+[a-z]{2}",ipaddr)
```

However, even that isn't going to help much because you're now just detecting the immediate parent of the "address" child object (which is `family inet` or `family inet6`).  Since it looks like you really want to associate interface names with addresses, you should really do this:

```python
parse = CiscoConfParse(config, syntax='junos', comment='#')
branchspec = (
    r'interfaces',
    r'^\s+\S+',   # Detect any intf name...
    r'^\s+unit',
    r'^\s+family',
    r'^\s+address',
)
for params in parse.find_object_branches(branchspec):

    intf_obj, intf_family_obj, addr_obj = params[1], params[3], params[4]

    intf_name = intf_obj.re_match_typed('^\s+(\S+)')
    intf_family = intf_family_obj.re_match_typed('\s+family\s+(inet\S*)')
    addr = addr_obj.re_match_typed('^\s+address\s+(\S+)')

    print("{} {} {}".format(intf_name, intf_family, addr))
```

The output is:

```
xe-0/0/0 inet 1.1.1.6/31
xe-0/0/0 inet6 FD00:DEAD:CAFE:6000::4/127
xe-0/0/1 inet 2.2.2.10/31
xe-0/0/1 inet6 FD00:DEAD:CAFE:7903::2/64
xe-0/0/2 inet 3.3.3.14/31
xe-0/0/2 inet6 FD00:DEAD:CAFE:6000::26/127
```

`find_object_branches()` is new to ciscoconfparse (do `pip install -U ciscoconfparse` to get the latest version), but I added it for exactly this use-case.  You could also do several nested `find_foo_w_bar()` loops, but grabbing all the objects at once is much cleaner...

The docs for `find_object_branches()` is [here](http://www.pennington.net/py/ciscoconfparse/api_CiscoConfParse.html?highlight=find_object_branches#ciscoconfparse.CiscoConfParse.find_object_branches)

**Comment by frederic-loui** [comment]
Hi Mike !
Meanwhile, I used a genuine `ciscoconfparse` parse library from `Debian buster` as `find_object_branches` was not available in this version and test it. It worked like a charm. :)
The library evolved since 2008 !
Thanks again for this excellent piece of work!
Frederic
