### ISSUE TITLE
VLAN parsing/diffing of "blobs" of config

### ISSUE THREAD

**Issue by lingfish** [mpenning/ciscoconfparse#22]
(As asked via mail, here's the issue)

Love your python package, but I'm struggling to work out how I can achieve something.

Put simply, I want to sync VLAN configs across my devices.  I want to use one device as the seed or master, and generate diffs to the rest.

Lines such as:

```
    vlan 51
     name SOME-VLAN
    vlan 52
     name BLAH
```

I've tried using `req_cfgspec_all_diff`, but this goes line by line.  I need those lines above I guess to be treated as a two line object instead, because a device may have the `vlan 51` line, but be missing the `name`... or extraneous `vlan` definitions may exist at a destination that I want to remove.

In essence, rsync for vlans ;)

**Comment by mpenning** [comment]
Due to my schedule lately, it took a lot longer to respond, but please take a look ``sync_diff()`` in  ciscoconfparse/master and let me know what you think.  I have been tweaking this off and on for a while, and it seems to mostly behave the way I want (>80% of the time).  For your use case, it looks good to me.

This is an example of the usage...

    from ciscoconfparse import CiscoConfParse
    #!!!!!!!!! Vlan test

    BROKEN = """!
    vlan 51
     state active
    vlan 53
    !""".splitlines()

    WORKING = """!
    vlan 51
     name SOME-VLAN
     state active
    vlan 52
     name BLAH
     state active
    !
    """.splitlines()

    linespec = r'vlan\s+\S+|name\s+\S+|state.+'
    parse = CiscoConfParse(BROKEN)
    diff = parse.sync_diff(WORKING, linespec, linespec)

When you run that, you'll get this in the ``diff`` variable...

    ['no vlan 53', 'vlan 51', ' name SOME-VLAN', 'vlan 52', ' name BLAH', ' state active']

Which is the config diff you need to sync those vlan configurations.  Again, I'm not finished with this code, but I think it's good enough for your use case right now... frankly it's been that way for almost a week, but this fails in some of my corner cases and I was hoping to make one big commit that fixed everything.

Anyway, let me know whether this works for you.

**Comment by mpenning** [comment]
This feature is formally available in 1.2.11.

@CrackerJackMack, this might be useful for your config audits

**Comment by CrackerJackMack** [comment]
@mpenning nice!

**Comment by lingfish** [comment]
Hi, sorry for the delays.

I've been giving this a quick spin, and it seems mostly ok?  The issues I think are potential difference in whitespace indentation etc (eg. one space from IOS, two from NXOS etc).  If we then ignore whitespace, we kind of lose the "grouping" if you will of `^vlan [0-9]+` and `^ +name`.

It almost needs to be a multiline, grouped diff, and not line by line.

**Comment by mpenning** [comment]
@lingfish,

Regarding whitespace, which version are you testing against, and what exactly failed.  Please provide an explicit example.  I [added explicit unit tests in 398da77](https://github.com/mpenning/ciscoconfparse/commit/398da77d2abcc61483fb39dc258f70cfa7905b2b#diff-5b11bc5903a1537f32703b230caca5c0) (to master, a few commits ahead of 1.2.14) and [nothing is broken](https://travis-ci.org/mpenning/ciscoconfparse/jobs/54072944).

Regarding grouped diffs, I've already started that, but I have a few more enhancements coming.  It's still a bit dumb, but if you look at [``config_heirarchy()``](https://github.com/mpenning/ciscoconfparse/blob/8fc03628410ec256fac3c1435ed7cbc5bd3d1af2/ciscoconfparse/ciscoconfparse.py#L2060), you'll see that I'm already preparing to group diffs by oldest parent

**Comment by mpenning** [comment]
The feature looks reasonably good for now.  Please file a bug if you find a problem.
