### ISSUE TITLE
loguru 0.5.3 vulnerability CVE-2022-0329

### ISSUE THREAD

**Issue by Tspinler** [mpenning/ciscoconfparse#223]
I am using ciscoconfparse==1.6.31 installed via pip.  There is a vulnerability in loguru 0.5.3 (CVE-2022-0329) which is a requirement for ciscoconfparse.  Recommended action is to upgrade loguru to 0.6.0.

**Comment by dwenjii** [comment]
I checked [Delgan/loguru](https://github.com/Delgan/loguru/) for evidence of the problem, but the CVE appears to be invalid.   Please refer to the following resources:
- The text of CVE-2022-0329: [This CVE has been rejected as it was incorrectly assigned. All references and descriptions in this candidate have been removed to prevent accidental usage.](https://nvd.nist.gov/vuln/detail/CVE-2022-0329).  In other words, "There is nothing to see here. Move on"
- [GHSA for Delgan/loguru](https://github.com/advisories/GHSA-cvp7-c586-cmf4) - This advisory has been withdrawn after the maintainers of loguru noted this issue is not a security vulnerability and the CVE has been revoked.  The GHSA was officially withdrawn on 1 Feb 2022
- [Delgan/loguru Issue #563](https://github.com/Delgan/loguru/issues/563)
  - [Github Product Management's repsonse](https://github.com/Delgan/loguru/issues/563#issuecomment-1025223732)
  - diffs to improve loguru [Remove use of "pickle.loads()" to comply with security tools](https://github.com/Delgan/loguru/commit/4b0070a4f30cbf6d5e12e6274b242b62ea11c81b) - January 21, 2022
- [Hacker News coverage of this issue](https://news.ycombinator.com/item?id=30128872)
- Blog post - [CVE-2022-0329 and the problems with automated vulnerability management](https://tomforb.es/cve-2022-0329-and-the-problems-with-automated-vulnerability-management/)

In the interest of keeping up with the latest loguru release, I have pushed a change to my git development branch to use the new loguru version (0.6.0).  This is not suggesting that there is any security vulnerability to use loguru version 0.5.3.

**Comment by mpenning** [comment]
I checked [Delgan/loguru](https://github.com/Delgan/loguru/) for evidence of the problem, but the CVE appears to be invalid.   Please refer to the following resources:
- The text of CVE-2022-0329: [This CVE has been rejected as it was incorrectly assigned. All references and descriptions in this candidate have been removed to prevent accidental usage.](https://nvd.nist.gov/vuln/detail/CVE-2022-0329).  In other words, "There is nothing to see here. Move on"
- [GHSA for Delgan/loguru](https://github.com/advisories/GHSA-cvp7-c586-cmf4) - This advisory has been withdrawn after the maintainers of loguru noted this issue is not a security vulnerability and the CVE has been revoked.  The GHSA was officially withdrawn on 1 Feb 2022
- [Delgan/loguru Issue #563](https://github.com/Delgan/loguru/issues/563)
  - [Github Product Management's repsonse](https://github.com/Delgan/loguru/issues/563#issuecomment-1025223732)
  - diffs to improve loguru [Remove use of "pickle.loads()" to comply with security tools](https://github.com/Delgan/loguru/commit/4b0070a4f30cbf6d5e12e6274b242b62ea11c81b) - January 21, 2022
- [Hacker News coverage of this issue](https://news.ycombinator.com/item?id=30128872)
- Blog post - [CVE-2022-0329 and the problems with automated vulnerability management](https://tomforb.es/cve-2022-0329-and-the-problems-with-automated-vulnerability-management/)

In the interest of keeping up with the latest loguru release, I have pushed a change to my git development branch to use the new loguru version (0.6.0).  This is not suggesting that there is any security vulnerability to use loguru version 0.5.3.
