### ISSUE TITLE
Adjust regex for VRF to include IOSXR config style

### ISSUE THREAD

**Issue by mjohnste** [mpenning/ciscoconfparse#235]
Adjust the vrf() property method to include a regex which matches IOSXR style VRF interface definition.

```
@property
def vrf(self):
    retval = self.re_match_iter_typed(
        r"^\s*(ip\s+)*vrf\sforwarding\s(\S+)$", result_type=str, group=2, default=""
    )
    return
```

The IOSXR VRF interface config is:
```
interface NAME
 vrf VRFNAME
```

**Comment by mpenning** [comment]
I just pushed the new `ciscoconfparse/models_iosxr.py` to `main`.

I'm in the middle of preparing for some major feature additions in `1.7.0` so this won't hit pypi for a while yet.  Nonetheless, you can get the new `models_iosxr.py` file from github.  I doubt this is going to be useful yet because I've never focused an effort on iosxr config parsing yet.
