### ISSUE TITLE
[Bug]: IOSIntfLine object incorrectly parses an interface description containing a single character

### ISSUE THREAD

**Issue by vladimirs-git** [mpenning/ciscoconfparse#272]
### Contact Details

dzhedaj@gmail.com

### What happened?

IOSIntfLine object interface description return empty string in case if description containing a single character

my vision of how to solve it, in the pull request https://github.com/mpenning/ciscoconfparse/pull/269

### CiscoConfParse Version

1.7.18

### What Operating System are you using?

Microsoft Windows

### What Python version(s) have this problem?

Python 3.10

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse

text = """
interface Ethernet1/1
  description A
"""

ccp = CiscoConfParse(text.splitlines(), factory=True)
intf = ccp.find_objects("^interface .+")[0]
descr = intf.description

assert descr == "A"
```

### Python tracebacks

```shell
no traceback
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
Hello @vladimirs-git 

I removed the 'bug' tag because `CiscoConfParse(foo, factory=True)` is not officially supported.

Please do not modify anything in `conftest.py` for this PR.

Please change your PR to reflect this regex... in `class BaseIOSIntfLine()`.
```
    retval = self.re_match_iter_typed(
        r"^\s*description\s+(\S.*)$", result_type=str, default=""
     )
     return retval
```

```python
from ciscoconfparse import CiscoConfParse

CONFIG = """!
interface Ethernet1/1
 description A
!
"""
parse = CiscoConfParse(CONFIG.splitlines(), factory=True)
objs = parse.find_objects("^interface")
for obj in objs:
    print("INTF         '{}'".format(obj))
    print("DESCRIPTION: '{}'".format(obj.description))
```

When I run that after I changed your PR, `obj.description` returns your single-character interface description.

```shell
 $ python gh269.py
INTF         '<IOSIntfLine # 1 'Ethernet1/1' info: 'No IPv4'>'
DESCRIPTION: 'A'
```

**Comment by mpenning** [comment]
Thank you for filing this issue.  I try to avoid making changes to test objects in `tests/conftest.py` because they are used all over my test suite.  My test for this is in [this github commit hash](https://github.com/mpenning/ciscoconfparse/commit/33278d039f2e63bdf1f76baa273710f67e4ece63).

Version 1.7.21 and later will have the fix.  The package is on pypi

**Comment by vladimirs-git** [comment]
thanks 👍
