### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'deprecat' persists on python 3.6

### ISSUE THREAD

**Issue by wouterdb** [mpenning/ciscoconfparse#276]
### Contact Details

wouter@inmanta.com

### What happened?

Our cisco deployment test pipeline collapsed due to https://github.com/mpenning/ciscoconfparse/issues/274

The current resolution does not solve this, because the bad packages report they are compatible with python 3.6, while the latest one with the fix does not. 

Could you please yank the bad packages from pypi? 

### CiscoConfParse Version

1.7.23

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.6

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
on pytohn3.6

pip install ciscoconfparse
python3 
import ciscoconfparse
```
```


### Python tracebacks

```shell
No module named 'deprecat'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by wouterdb** [comment]
Duplicates #277

**Comment by mpenning** [comment]
You have correctly identified a known packaging problem; however, manually installing dependencies works.  As such, I should not delete versions 1.7.21 through 1.7.23 from pypi.  Some people may have pinned those releases (and their copies work because they already installed dependencies).

FYI, Python 3.6 is no longer supported by python.org.  The last supported release was in 2021.
