### ISSUE TITLE
Import issues on 3.4.3 with CiscoConfParse > 1.2.14.

### ISSUE THREAD

**Issue by FozzieBear** [mpenning/ciscoconfparse#32]
CiscoConfParse 1.2.15 and greater appear to have issues importing correctly in Python 3.4.3 under Windows 7. Rolling back, 1.2.14 is the last version that appears to work as expected. Example below using 1.2.17.

```python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

>>> from ciscoconfparse import CiscoConfParse
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from ciscoconfparse import CiscoConfParse
ImportError: cannot import name 'CiscoConfParse'

>>> from ciscoconfparse import ciscoconfparse
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from ciscoconfparse import ciscoconfparse
  File "C:\Users\user\virtuals\test_env\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 8, in <module>
    from models_cisco import IOSHostnameLine, IOSRouteLine, IOSIntfLine
ImportError: No module named 'models_cisco'

```

**Comment by mpenning** [comment]
Thank you for reporting this problem...  I can replicate the issue with Python 3.4.3 in Windows Vista as well.

I confirmed that Python 2.7 + ``ciscoconfparse ``in Windows *does not* have this problem; at this point, my best workaround is to go with Python 2.7 in Windows.

![ccp_1_2_17_windows](https://cloud.githubusercontent.com/assets/36991/7022291/d0cc5410-dcef-11e4-83ba-ba3f2ff3edbd.png)


Python3.4 + ``ciscoconfparse`` also works in linux.

I'm still trying to parse what exactly broke this... sadly there is [no Travis-CI Windows support](https://github.com/travis-ci/travis-ci/issues/216), and it's all to easy for me to ``make devtest`` + ``make repo-push`` with no visibility to windows packaging problems.

**Comment by mpenning** [comment]
This problem was introduced by [``setup.py`` commit ``72240ce89b76143a3383e730ce16054cf66a9e0a``](https://github.com/mpenning/ciscoconfparse/commit/72240ce89b76143a3383e730ce16054cf66a9e0a#diff-2eeaed663bd0d25b7e608891384b7298) when I disabled the ``use_2to3`` flag.

Reverting that change fixes the problem on my system; please test on your system and let me know.  I took the liberty of pushing version 1.2.18 to pypi, since I know it fixes Py34 + ciscoconfparse problems in Windows Vista.

![ccp_1_2_18_windows](https://cloud.githubusercontent.com/assets/36991/7043870/39b22d74-ddb3-11e4-9c99-1dbb0976a456.png)

**Comment by FozzieBear** [comment]
1.2.18 confirmed working here on Windows 7 with 3.4.3 via pypi. Thanks for the quick response!
