### ISSUE TITLE
Junos vs IOS codebase compatibility

### ISSUE THREAD

**Issue by mahtin** [mpenning/ciscoconfparse#38]
The codebase for Junos and IOS don't quite stay in sync (this is 100% understandable). A quick diff shows the missing parts.

`sed -e 's/junos/cisco/g' -e 's/Junos/IOS/g' < ciscoconfparse/models_junos.py | diff ciscoconfparse/models_cisco.py - | more`

Maybe some `NotImplementedError` additions could help point this out and mark the points where code needs to be written in order to support both platforms.

One other thing noted includes the `self._address_family = "ipv6"` variable being different in the two files.

**Comment by mpenning** [comment]
Thank you for raising a question.

You are comparing APIs in ``models_junos.py`` to ``models_cisco.py``.  However,I don't think [``models_cisco.py``](https://github.com/mpenning/ciscoconfparse/blob/2372afe378c8e26670662d8c8e34861558a2acdd/ciscoconfparse/models_cisco.py) and ``models_junos.py`` will *ever* have API parity because [``models_cisco.py``](https://github.com/mpenning/ciscoconfparse/blob/2372afe378c8e26670662d8c8e34861558a2acdd/ciscoconfparse/models_cisco.py) implements some features that are cisco-specific.  For instance, it doesn't make sense to add [cdp](https://github.com/mpenning/ciscoconfparse/blob/2372afe378c8e26670662d8c8e34861558a2acdd/ciscoconfparse/models_cisco.py#L1099), [rapid-pvst](https://github.com/mpenning/ciscoconfparse/blob/2372afe378c8e26670662d8c8e34861558a2acdd/ciscoconfparse/models_cisco.py#L1364), or [hsrp](https://github.com/mpenning/ciscoconfparse/blob/2372afe378c8e26670662d8c8e34861558a2acdd/ciscoconfparse/models_cisco.py#L1120) features into a Junos parser.

If you have specific features you'd like implemented, please list them in this GH issue... also please provide a scrubbed Junos config which implements the features since I don't have ready access to Junos configs these days.
