### ISSUE TITLE
Cannot build a universal wheel

### ISSUE THREAD

**Issue by HenryGessau** [mpenning/ciscoconfparse#47]
Because of the conditional in setup.py for IPADDR and DNSPYTHON it is not possible to build a universal wheel for this package.

**Comment by fungi** [comment]
I know ciscoconfparse does not currently upload wheels to PyPI, but the issue is that more recent pip releases build wheels from every sdist they download (when possible) and cache them for the user. It appears that ciscoconfparse successfully builds a wheel and the result claims to be universal, but since wheels are static the conditional logic within setup.py is resolved at wheel build time and is therefore only relevant to the Python version under which it was generated (i.e., not universal) so subsequent use of pip with a different interpreter version can end up using the wrong dependency determination and break.

The simple solution is to stop declaring ciscoconfparse wheels universal, though a better long-term fix is to implement PEP 426 environment markers. https://www.python.org/dev/peps/pep-0426/#environment-markers

**Comment by mpenning** [comment]
More discussion about the ciscoconfparse and openstack builds

http://eavesdrop.openstack.org/irclogs/%23openstack-infra/%23openstack-infra.2015-08-24.log.html
