### ISSUE TITLE
Linenum off-by-one

### ISSUE THREAD

**Issue by lllama** [mpenning/ciscoconfparse#80]
Not sure if I've missed something in the docs, but it looks like `linenum`s are zero-indexed, which doesn't match up to the docs.

Is it correct that the first line in a config has a `linenum` of 0?

**Comment by mpenning** [comment]
I can see why this might be a bit confusing given that parts of the [parent-child tutorial](http://www.pennington.net/py/ciscoconfparse/tutorial_parent_child.html#ios-parent-child-relationships) talk casually about some configurations and do so with config-lines starting at one.  This is just because humans typically start their numbering at one.

However, this library has always assumed that the machine-parsed line-numbers start at zero... for example, consider the discussion under [Example: Retrieving text from an IOSCfgLine object](http://www.pennington.net/py/ciscoconfparse/tutorial_parent_child.html#example-retrieving-text-from-an-ioscfgline-object).  The second line of the configuration ('interface Serial1/0') is line-number 1 in that example.

If there are places in the documentation that show inconsistencies in the machine-parsed line numbers then please let me know; I will be happy to correct that.
